### PR TITLE
Increase performance of index removing operations for big collections

### PR DESCRIPTION
**Pull request by Jimilian**
It should help in case of https://github.com/fakemongo/fongo/issues/151.

### CODE REVIEW

**Comment by twillouer** [comment]
Hi,

thanks. have you test against the "PerfTest" class ?

**Comment by Jimilian** [comment]
Hi! Without my changes:
```
Took 422 ms
Took 304 ms with one useless index.
Took 12955 ms with no index.
Took 19838 ms with index.
```
With my changes:
```
Took 468 ms
Took 533 ms with one useless index.
Took 14561 ms with no index.
Took 19117 ms with index.
```
I didn't know about this tests, I can try to reduce effort for case without index and with one index. But I was trying to optimizing case with index changing.

**Comment by Jimilian** [comment]
If we are talking about removing:
* with my changes: 350 ms
* without my changes: 832 ms

**Comment by Jimilian** [comment]
Please, let me know, if you need some additional information/changes,

**Comment by Jimilian** [comment]
Current implementation:
Name | №1 | №2 | №3 | №4 | №5 | №6
------------ | ------------- | ------------- | ------------- | ------------- | ------------- | -------------
Simple | 431 | 438 | 420 | 388 | 439 | 371
Useless index | 401 | 338 | 339 | 314 | 420 | 328
With no index | 12235 | 12201 | 14932 | 11834 | 11220 | 12298
With index | 18599 | 23628 | 24962 | 18655 | 18737 | 22383

New one:
Name | №1 | №2 | №3 | №4 | №5 | №6
------------ | ------------- | ------------- | ------------- | ------------- | ------------- | -------------
Simple | 398 | 375 | 403 | 395 | 364 | 389
Useless index | 403 | 381 | 342 | 483 | 381 | 380
With no index | 11914 | 14341 | 11836 | 12206 | 12507 | 12371
With index | 20874 | 22150 | 19057 | 17290 | 18684 | 18405

Performance test has a flaky results, so, I made a several iterations - to remove side-effects. Current result shows that new implementation doesn't create performance effort.
Also, current tests are not testing contains/remove/add methods, that's why we can't see any performance increasing for new implementation.

**Comment by twillouer** [comment]
thanks !

**Pull request merged**
