### PR TITLE
Adding $lookup support in fongodb

### PR DESCRIPTION
**Pull request by krraghavan**
Added $lookup support

### CODE REVIEW

**Comment by twillouer** [comment]
Hi,

thanks for the contribution, but can you take a look to the new 'master' branch.
I think it's the reason of conflicts ?

**Comment by krraghavan** [comment]
Hi William, this being my first commit, I don't want to screw it up.  Do
you mind giving me the instructions to resolve the conflicts
Thx
Raghavan

**Comment by twillouer** [comment]
Hi,

this is your commit ? https://github.com/krraghavan/fongo/commit/30eb6d42845c2e2d893df3b17a6942bad3344cec

**Comment by krraghavan** [comment]
Yes
Raghavan 

Please pardon my brevity and any typos as this mail is sent from my mobile device

**Comment by krraghavan** [comment]
Figured it out and updated.  No conflicts now. But I am using Java 8 classes which causes CI to fail.  Will fix.

**Comment by krraghavan** [comment]
Compilation succeeded for JDK 7 and 8 - this is not a class I changed or created.  Looks like an incompatible driver problem.

Tests in error: 
  JongoGeoTest.before:61 » UnsupportedClassVersion de/undercouch/bson4jackson/Bs...
  JongoGeoTest.before:61 » UnsupportedClassVersion de/undercouch/bson4jackson/Bs...
  JongoGeoTest.before:61 » UnsupportedClassVersion de/undercouch/bson4jackson/Bs...
  FongoJongoTest.setup:31 » UnsupportedClassVersion de/undercouch/bson4jackson/B...
  FongoJongoTest.setup:31 » UnsupportedClassVersion de/undercouch/bson4jackson/B...
  FongoJongoTest.setup:31 » UnsupportedClassVersion de/undercouch/bson4jackson/B...
  FongoJongoTest.setup:31 » UnsupportedClassVersion de/undercouch/bson4jackson/B...
  FongoJongoTest.setup:31 » UnsupportedClassVersion de/undercouch/bson4jackson/B...
  FongoJongoTest.setup:31 » UnsupportedClassVersion de/undercouch/bson4jackson/B...
  FongoJongoTest.setup:31 » UnsupportedClassVersion de/undercouch/bson4jackson/B...
  FongoJongoTest.setup:31 » UnsupportedClassVersion de/undercouch/bson4jackson/B...
  FongoJongoTest.setup:31 » UnsupportedClassVersion de/undercouch/bson4jackson/B...
  FongoJongoTest.setup:31 » UnsupportedClassVersion de/undercouch/bson4jackson/B...
  FongoJongoTest.setup:31 » UnsupportedClassVersion de/undercouch/bson4jackson/B...
  FongoCastTest.checkFongoSupportsMajority »  Unexpected exception, expected<com...

**Comment by krraghavan** [comment]
I changed the version for Jongo even though it is not something I added.  Java 6 compilation was failing with the latest Jongo version included in the pom.

**Comment by krraghavan** [comment]
Can you tell me if there is a problem with this PR?  Just wanted to know if I should close it.

**Comment by twillouer** [comment]
can you check against the master branch if all is fine ?

**Comment by krraghavan** [comment]
Merged with latest upstream master.

**Comment by twillouer** [comment]
Hi,

normally, all is fine in "master" (and I change some test from java 8 to java 6) :)

In this PR, there only some change on author name (it's fine), but the DeadlockIT is not necessary no ?

**Comment by krraghavan** [comment]
Yes - you are correct.  Happened after the merge.  Will fix and resubmit
Raghavan

**Comment by twillouer** [comment]
Thx

**Comment by krraghavan** [comment]
Any idea when 2.0.8 might be released.  I'm creating a new open source project which includes annotation support for Mongo aggregate queries much like what Spring DB Mongo provides for regular queries and I need 2.0.8 for the lookup support that it provides.

**Comment by twillouer** [comment]
ok ok, tomorrow :)

**Comment by krraghavan** [comment]
Thx
Raghavan

**Comment by twillouer** [comment]
2.0.9 uploaded

**Comment by krraghavan** [comment]
Just a small nit - please update the contributor list when you get a chance.
Raghavan

**Pull request merged**
