### PR TITLE
fixes #186: BulkWrite upsert w/o _id in query returns empty upserts

### LINKED ISSUE #186: BulkWrite upsert not returning correct BulkWriteResult
I'm using Fongo 2.0.5 and the 3.2.1 Mongo java drivers.

bulkWrite with UpdateOneModel and UpdateOptions.upsert(true) is not returning any information in the BulkWriteResult when it does in fact perform an upsert.  This appears to be because the upserted DbObject doesn't have "_id" (see [FongoDBCollection#L307](https://github.com/fakemongo/fongo/blob/fongo-2.0.5/src/main/java/com/mongodb/FongoDBCollection.java#L307) and [FongoDBCollection#L1174](https://github.com/fakemongo/fongo/blob/fongo-2.0.5/src/main/java/com/mongodb/FongoDBCollection.java#L1174)

I have Scala code that inspects the BulkWriteResults & needs to retrieve the IDs of the upserts for further processing.  The code works correctly against live MongoDB 3.2 and 3.0 but my unit tests of the code fail.

I'll try construct a minimal failing example, because adding an UpdateOneModel to the Fongo unit test actually succeeds.

### PR DESCRIPTION
**Pull request by worrel**
Fixes missing BulkWriteUpsert for bulk updates with upsert=true that have no _id in query

### CODE REVIEW

**Comment by twillouer** [comment]
Thanks, can you see why travis is not happy ?

**Comment by worrel** [comment]
@twillouer the travis failures are related to the JMH generated classes (from #165).  I get them locally if i run the travis Maven cmdline(s), but they go away if I prepend a "clean" e.g.
```mvn clean install -DskipTests=true -Dmaven.javadoc.skip=true -B -V``` and ```mvn clean test -B```.

However, once the build works, my unit test is now failing - perhaps some interaction with the recently merged PRs on MASTER.  I'll fix & update.  Related question - should I just target MASTER instead of v3?

**Comment by twillouer** [comment]
Hi,

no, for 2.0X it's "v3". master is for old drivers..

**Comment by worrel** [comment]
@twillouer OK, I'll stay on v3. I'm tracking down a unit test failure, it's failing for ServerVersion0 test but working for ServerVersion3.

**Comment by worrel** [comment]
Fixed some edge cases & added more tests.  Builds fine locally by adding "clean" to both "mvn" lines from Travis.  I suggest we find a way to isolate the JMH PerfTest via a Maven profile since it's breaking this & #172

**Comment by twillouer** [comment]
Right !

**Comment by worrel** [comment]
I see this is marked for 2.0.6 - do you have a timeline for when that might be released? Our build scripts & env are not well setup for pulling MASTER or snapshot dependencies :disappointed:

**Comment by twillouer** [comment]
when you need :)

**Pull request merged**
