### PR TITLE
Exception missmatch between Fongo and MongoDB on findAndModify with unique index

### PR DESCRIPTION
**Pull request by scho**
Given the following data structure:
```json
{
  "_id": "someId",
  "value": "someValue"
}
```
There is a unique index on `value`.

If I try to update a document using `findAndModify` and set `value` to an already existing `value` in the collection, the following happens:

Fongo throws a `com.mongodb.DuplicateKeyException`.
MongoDB throws a `com.mongodb.MongoCommandException`.

MongoDB driver version: `3.2.0`
MongoDB version: `3.2.4`
Fongo version: `2.0.6`

Is there a way I can provide a PR? If so, please point me into a direction and I'll try my best :)

### CODE REVIEW

**Comment by scho** [comment]
I could only find the `AbstractFongoV3Test` class in the `v3` branch, so I picked that one. Not sure if was correct though.

**Comment by twillouer** [comment]
Thnaks !

**Comment by scho** [comment]
One remark:
This behavior is a known bug in MongoDB:
https://jira.mongodb.org/browse/JAVA-1821

**Comment by ipavkovic** [comment]
Looks like
- mongo java driver 3.3.0 now throws a com.mongodb.DuplicateKeyException, 
- Fongo > 2.0.6 throws a com.mongodb.MongoCommandException

**Pull request merged**
