### PR TITLE
Issue 242

### PR DESCRIPTION
**Pull request by nicolaViola**
I have created a test to check if the collection has a valid name.
I added a check of the  collection name is valid in FongoConnection
I added a SuitTest to run all test together

### CODE REVIEW

**Comment by nicolaViola** [comment]
Sorry if I created a X file, I removed it. It was only a test because it is my first time to pull a request.
Best regards

**Comment by mchildspelco** [comment]
The part of this change that checks for the collection starting with 'system.' instead of only 'system' would really help me out. I have a hunch that that was the intent of the mongo developers even though the online mongo documentation suggests otherwise:

"MongoDB stores system information in collections that use the <database>.system.* namespace, which MongoDB reserves for internal use. Do not create collections that begin with system."
(https://docs.mongodb.com/manual/reference/system-collections/)

**Comment by twillouer** [comment]
Hi,

thank you !
Can you remove the TestSuite ?

**Comment by nicolaViola** [comment]
I think I have deleted TestSuit.java

**Pull request merged**
