### PR TITLE
Tests that #171 is fixed

### PR DESCRIPTION
**Pull request by mrmanc**
Tests there are no class casting issues with how FongoDBCollection uses com.mongodb.WriteConcern.

### CODE REVIEW

**Comment by twillouer** [comment]
Hi,

thanks for the PR.

any idea why travis is not happy ?

**Comment by mrmanc** [comment]
Apologies… I hadn't realised. I'll take a look tomorrow!

**Comment by mrmanc** [comment]
Looks like the travis build was is failing for the same reason that the v3 branch was already failing. I think commit 3f9fffc may have caused the it to start breaking, but it passes locally. I tried running both mvn tasks and could not reproduce the failure. Looking at what is happening I suspect the first mvn command (`mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V`) causes the JMH classes to be auto generated and so they are found to be duplicates when `mvn test -B` runs.

**Comment by twillouer** [comment]
Thanks, sorry to be late !

**Comment by mrmanc** [comment]
Thanks and no problem… we all have other things to do :) :+1:

**Pull request merged**
