### PR TITLE
A string in a query value is not attempted to be parsed as a Date before comparing

### PR DESCRIPTION
**Pull request by libetl**
I think we should try to parse it before considering it as a real String.

### CODE REVIEW

**Comment by libetl** [comment]
This query should work in fongodb : {"creationDate":{"$gt", "2015-01-06"}}
It does not because the date value is of type String. We should try to parse it.

**Comment by twillouer** [comment]
Thanks !

**Comment by twillouer** [comment]
Hi @libetl,

do you have a reference for this ?

I try to reproduce on a real mongodb, and this is not working

```
> db.db.find();
{ "_id" : 1234, "var1" : "val1", "created" : ISODate("2015-02-04T00:02:01.719Z") }
{ "_id" : 2345, "var1" : "val2", "created" : ISODate("2015-02-06T00:02:01.719Z") }

> db.db.find({created:{$gte:ISODate("2015-02-04T00:02:01.719Z")}});
{ "_id" : 1234, "var1" : "val1", "created" : ISODate("2015-02-04T00:02:01.719Z") }
{ "_id" : 2345, "var1" : "val2", "created" : ISODate("2015-02-06T00:02:01.719Z") }

> db.db.find({created:{$gte:ISODate("2015-02-04")}});
{ "_id" : 1234, "var1" : "val1", "created" : ISODate("2015-02-04T00:02:01.719Z") }
{ "_id" : 2345, "var1" : "val2", "created" : ISODate("2015-02-06T00:02:01.719Z") }
> db.db.find({created:{$gte:"2015-02-04"}});
```

and :
```
> db.db.find({created:{$gte:"2015-02-04"}});
> 

```

I also check your TestCase againts MongoDB (if you pass FongoRule(true) it check againts a real mongodb instance) and you test fail.

Can you provide me more information ?

**Comment by libetl** [comment]
Hello,

That was a mistake. I cannot figure out why, but when I insert an ISO date in string format (i.e. "2014-01-07T13:33:57.229Z"), it is converted automatically in a real ISODate. Is it related to the java mongo driver ?

I am going to revert the change. It is not supposed to work.

**Comment by libetl** [comment]
if you want to query a date, in mongo shell, you can use the $date operator (>= 2.6).

**Pull request merged**
